name: FutureTagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
env:
  JULIA_PKG_SERVER_REGISTRY_PREFERENCE: 'eager'
permissions:
  contents: write
jobs:
  FutureTagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: true
          fetch-depth: 0
          ssh-key: '${{ secrets.FUTURETAGBOT_PRIVATE_KEY }}'
      - uses: julia-actions/setup-julia@b315a4d9881690c63d53fc0175b150a3776140bd
        with:
          version: '1'
      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: "Install FutureTagBot"
        run: |
          import Pkg
          name = "FutureTagBot"
          uuid = "aad37465-2b3a-4ede-b4ea-f5792ced75b4"
          url = "https://github.com/JuliaRegistries/FutureTagBot.jl.git"
          # version = "1"
          Pkg.add(; name, uuid, url)
        shell: julia --color=yes {0}
      - name: "Run FutureTagBot"
        run: |
          import FutureTagBot
          FutureTagBot.main(; path = pwd())
        shell: julia --color=yes {0}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
